<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <link rel="stylesheet" type="text/css" href="/styles/styles.css" />
</head>
<body>
<div id="content-page">
    <?php echo $this->render('_header.phtml') ?>

    <div id="content-body">
        <div id="side-content-left">
            <div id="side-menu">
                <?php echo $this->navigation() ?>
            </div>
        </div>
        <?php echo $this->layout()->content ?>
    </div>
    <?php echo $this->render('_footer.phtml') ?>
</div>
</body>
</html>